Added problem frame and identity focus content
Umuzi-org/syllabus-product-design pull request #10
Opened 2021-07-07 19:08 UTC by hloniphile22

2021-07-12 18:05 UTC, kaleem99 requested changes
pls, run "npm run validate" to check for validation errors and remove line 5 in the problem-frame-and-ident folder file, use Grammarly to check for spelling errors, other than that everything else looks good.

2021-07-13 07:06 UTC, sheenarbw requested changes
Please ask Kaleem to help if you aren't sure how to run the `npm run validate` thing

2021-07-13 07:06 UTC, sheenarbw commented on content/problem-frame-and-identity-focus/index.md
> +ready: true
ready:true should always be removed.

Please remember to run `npm run validate` in the terminal

2021-08-03 14:31 UTC, kaleem99 approved these changes

2021-08-11 09:27 UTC, sheenarbw approved these changes

2021-08-11 09:27 UTC, merged