Added test your prototype
Umuzi-org/syllabus-product-design pull request #13
Opened 2021-07-07 19:50 UTC by hloniphile22

2021-07-13 07:18 UTC, sheenarbw requested changes

2021-07-13 07:18 UTC, sheenarbw commented on content/test-your-prototype/index.md
> +Your week began with a big challenge, and not much else. So far, you’ve created promising solutions, chosen the best, and built a realistic prototype. That alone would make for an impressively produc
This sentence might need to be revised - remember that tilde allows self paced learning. Is everyone going to start the same thing on the same day? What week are you referring to here?  You could say "Your bootcamp experience started off with a big challenge"

2021-07-13 07:18 UTC, sheenarbw commented on content/test-your-prototype/index.md
> +- A document with feedback from the user and the next steps i.e to go back or to move forward.
a google doc?  It really pays to be explicit. If there is a 10% chance that folks will get confused then 10% of them will get confused.

2021-08-05 15:25 UTC, kaleem99 approved these changes

2021-08-11 09:32 UTC, merged