Added google analytics content
Umuzi-org/syllabus-product-design pull request #5
Opened 2021-07-07 12:21 UTC by hloniphile22

2021-07-07 18:16 UTC, kaleem99 approved these changes
looks good.

2021-07-08 13:10 UTC, sheenarbw requested changes

2021-07-08 13:10 UTC, sheenarbw commented on content/google-analytics/index.md
> +Complete the Google Analytics for Beginners. This will roughly take 4-6 hours if completed sequentially. You have the choice of watching the videos or reading the transcripts. Complete all 4 short un
You might want to give people a bit more info on how to submit their work...

Tilde doesn't allow folks to upload screenshots.  I'd suggest "take a screenshot of your certificate and upload it to google drive. Please share a link to your screenshot"

Trust me, people will be annoying if you aren't clear on this stuff!

2021-07-13 07:02 UTC, sheenarbw approved these changes

2021-07-13 07:02 UTC, merged